// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REMOVED_API_KEY',
    appId: '1:605757642586:web:34b5422fe9c31c90e18563',
    messagingSenderId: '605757642586',
    projectId: 'kandas-e8cc7',
    authDomain: 'kandas-e8cc7.firebaseapp.com',
    storageBucket: 'kandas-e8cc7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REMOVED_API_KEY',
    appId: '1:605757642586:android:0afabf747b30de61e18563',
    messagingSenderId: '605757642586',
    projectId: 'kandas-e8cc7',
    storageBucket: 'kandas-e8cc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REMOVED_API_KEY',
    appId: '1:605757642586:ios:1e5840ad4eed63a5e18563',
    messagingSenderId: '605757642586',
    projectId: 'kandas-e8cc7',
    storageBucket: 'kandas-e8cc7.firebasestorage.app',
    androidClientId: '605757642586-kntmrdcclq3q91it1p6kd112cd315vmb.apps.googleusercontent.com',
    iosClientId: '605757642586-lopud8b4ofqtn6c942joq5siluj6u57q.apps.googleusercontent.com',
    iosBundleId: 'com.example.kandas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REMOVED_API_KEY',
    appId: '1:605757642586:ios:1e5840ad4eed63a5e18563',
    messagingSenderId: '605757642586',
    projectId: 'kandas-e8cc7',
    storageBucket: 'kandas-e8cc7.firebasestorage.app',
    androidClientId: '605757642586-kntmrdcclq3q91it1p6kd112cd315vmb.apps.googleusercontent.com',
    iosClientId: '605757642586-lopud8b4ofqtn6c942joq5siluj6u57q.apps.googleusercontent.com',
    iosBundleId: 'com.example.kandas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REMOVED_API_KEY',
    appId: '1:605757642586:web:34b5422fe9c31c90e18563',
    messagingSenderId: '605757642586',
    projectId: 'kandas-e8cc7',
    authDomain: 'kandas-e8cc7.firebaseapp.com',
    storageBucket: 'kandas-e8cc7.firebasestorage.app',
  );

}